### ISSUE TITLE
Anglican?

### ISSUE THREAD

**Issue by aaelony** [yieldbot/gp-blog#1]
This is not really an issue at all, just a way to ask you your thoughts on Anglican (e.g. http://www.robots.ox.ac.uk/~fwood/anglican/examples/viewer/?worksheet=gaussian-aistats)

cheers,
-A

**Comment by jimdunn** [comment]
Hi,
Actually the guy that got me curious about Gaussian processes also pointed out Anglican to me. I haven't had much time to play around with it, but I've heard good things. I will probably take a closer look eventually, but for now it's helpful and enjoyable for me to learn about GPs by cobbling together my own bits of code.

**Comment by aaelony** [comment]
Thanks as well for your blog posts.  Great stuff with core.matrix. Looking forward to the next one...
